export default {
    category1: [{
            menu_title: "Dashboard",
            menu_icon: "zmdi zmdi-view-dashboard",
            path: "/app/dashboard",
            new_item: false,
            child_routes: null,
        },
        {
            menu_title: "userManagement",
            menu_icon: "zmdi zmdi-settings",
            path: "/app/users",
            new_item: false,
            child_routes: null,
        },
        {
            menu_title: "category",
            menu_icon: "zmdi zmdi-widgets",
            path: "/app/category",
            new_item: false,
            child_routes: null,
        },
        {
            menu_title: "subCategory",
            menu_icon: "zmdi zmdi-group",
            path: "/app/subCategory",
            new_item: false,
            child_routes: null,
        },
        {
            menu_title: "banners",
            menu_icon: "zmdi zmdi-border-all",
            path: "/app/banner",
            new_item: false,
            child_routes: null,
        },
        {
            menu_title: "cms",
            menu_icon: "zmdi zmdi-format-list-bulleted",
            path: "/app/CMSPages",
            new_item: false,
            child_routes: null,
        },
    ],
};